// AUTO-GENERATED FILE. DO NOT EDIT.
// Run: node scripts/generateFoodIconItalianAliases.js

export const FOOD_ICON_ALIASES_IT: Record<string, string[]> = {
  "acai-berries": ["acai bacche"],
  "acerola-cherries": ["acerola ciliegie"],
  "achar-indian-mango-pickle": ["achar indiano mango pickle"],
  "acorn-squash": ["ghianda zucca"],
  "agave-nectar": ["agave nettare"],
  "alfalfa-sprouts": ["erba medica germogli"],
  "almond-butter": ["mandorla burro"],
  "almond-milk": ["mandorla latte"],
  "almonds": ["mandorle"],
  "amaranth": ["ingrediente amaranth"],
  "amber-nameko-mushrooms": ["ambra nameko funghi"],
  "american-cheese-slices": ["americano formaggio fette"],
  "americano-iced": ["americano freddo"],
  "amla-indian-gooseberry": ["amla indiano gooseberry"],
  "anaheim-pepper": ["anaheim pepe"],
  "anchovies-dried": ["acciughe essiccato"],
  "anchovies-fresh": ["acciughe fresco"],
  "angel-hair-pasta": ["angelo hair pasta"],
  "apple-cider-vinegar": ["aceto di mele"],
  "apple-freeze-dried-slices": ["mela liofilizzato essiccato fette"],
  "applesauce": ["purea di mela"],
  "apricot": ["albicocca"],
  "arbol-peppers": ["arbol peperoni"],
  "arctic-char-fillet-raw": ["artico char filetto crudo"],
  "aronia-berries": ["aronia bacche"],
  "artichoke-heart": ["artichoke cuore"],
  "arugula": ["rucola"],
  "asiago-cheese": ["asiago formaggio"],
  "asparagus": ["asparagi"],
  "avocado": ["ingrediente avocado"],
  "baby-corn": ["baby mais"],
  "bacon-bits": ["pancetta bits"],
  "bacon-strips-raw": ["pancetta strisce crudo"],
  "baguette": ["ingrediente baguette"],
  "balsamic-vinegar": ["aceto balsamico"],
  "banana-overripe": ["ingrediente banana overripe"],
  "banana-pepper": ["banana pepe"],
  "banana": ["ingrediente banana"],
  "barberries": ["ingrediente barberries"],
  "basa-fillet-raw": ["basa filetto crudo"],
  "basil-dried": ["basilico essiccato"],
  "basil": ["basilico"],
  "bay-leaf": ["alloro leaf"],
  "beef-brisket-raw": ["manzo brisket crudo"],
  "beef-ribs-raw": ["manzo costine crudo"],
  "beef-roast-raw": ["manzo arrosto crudo"],
  "beef-sausage": ["manzo salsiccia"],
  "beef-short-ribs-raw": ["manzo short costine crudo"],
  "beef-shoulder-raw": ["manzo spalla crudo"],
  "beef-sirloin-steak-raw": ["manzo controfiletto bistecca crudo"],
  "beets": ["barbabietole"],
  "belgian-endive": ["belgian indivia"],
  "black-bean-garlic-sauce": ["nero fagiolo aglio salsa"],
  "black-beans-canned": ["nero fagioli in scatola"],
  "black-beans-dry": ["nero fagioli secco"],
  "black-cardamom": ["nero cardamomo"],
  "black-caviar": ["nero caviale"],
  "black-cod-sablefish-fillet-raw": ["nero merluzzo sablefish filetto crudo"],
  "black-eyed-peas-lobia": ["nero eyed piselli lobia"],
  "black-gram-sabut-urad": ["nero gram sabut urad"],
  "black-mustard-seeds": ["nero senape semi"],
  "black-olives": ["nero olive"],
  "black-pepper-grinder": ["macina pepe nero"],
  "black-peppercorns": ["grani di pepe nero"],
  "black-raspberry": ["nero lampone"],
  "black-rice-vinegar": ["nero riso aceto"],
  "black-tea-leaves": ["nero te foglie"],
  "black-tea": ["nero te"],
  "black-truffle": ["nero tartufo"],
  "blackberry": ["mora"],
  "blackcurrant": ["ribes nero"],
  "blackeye-peas-canned": ["blackeye piselli in scatola"],
  "blackeye-peas-dry": ["blackeye piselli secco"],
  "blue-corn-tortillas": ["blu mais tortillas"],
  "blue-corn": ["blu mais"],
  "blue-mussels": ["blu cozze"],
  "blueberries": ["ingrediente blueberries"],
  "blueberry-freeze-dried": ["mirtillo liofilizzato essiccato"],
  "blueberry-muffin": ["mirtillo muffin"],
  "boba-drink": ["boba bevanda"],
  "bocconcini-cheese": ["bocconcini formaggio"],
  "bok-choy": ["ingrediente bok choy"],
  "boletus-mushroom": ["ingrediente boletus mushroom"],
  "boysenberry": ["ingrediente boysenberry"],
  "branzino": ["ingrediente branzino"],
  "bread-crumbs": ["pane pangrattato"],
  "bread-slice": ["pane fetta"],
  "breadstick": ["grissino"],
  "breakfast-sausage-patties": ["breakfast salsiccia polpette"],
  "brie-cheese": ["brie formaggio"],
  "brioche-bread": ["brioche pane"],
  "broccoli": ["ingrediente broccoli"],
  "brown-button-mushroom": ["marrone button mushroom"],
  "brown-chickpeas-kala-chana": ["ceci marroni kala chana"],
  "brown-coconut": ["marrone cocco"],
  "brown-egg": ["marrone uovo"],
  "brown-lentils": ["marrone lenticchie"],
  "brown-mustard-seeds": ["marrone senape semi"],
  "brown-rice-bowl": ["ciotola di riso integrale"],
  "brussels-sprouts": ["bruxelles germogli"],
  "burrata-cheese": ["burrata formaggio"],
  "butter-lettuce": ["burro lattuga"],
  "butter": ["burro"],
  "buttermilk": ["latticello"],
  "butternut-squash": ["butternut zucca"],
  "cabbage": ["cavolo"],
  "caesars-mushroom": ["ingrediente caesars mushroom"],
  "caffe-latte-iced": ["caffe latte freddo"],
  "calamansi": ["ingrediente calamansi"],
  "camembert-cheese": ["camembert formaggio"],
  "canadian-bacon": ["canadese pancetta"],
  "candy-cap-mushrooms": ["candy cap funghi"],
  "cannellini-beans-canned": ["cannellini fagioli in scatola"],
  "cannellini-beans-dry": ["cannellini fagioli secco"],
  "cantaloupe": ["ingrediente cantaloupe"],
  "capers": ["capperi"],
  "caramel-sauce": ["caramello salsa"],
  "carolina-reaper-pepper": ["carolina reaper pepe"],
  "carp-fish": ["carp pesce"],
  "carrot": ["carota"],
  "cashews": ["anacardi"],
  "catfish-fillet-raw": ["pesce gatto filetto crudo"],
  "cauliflower": ["ingrediente cauliflower"],
  "cayenne-pepper-powder": ["cayenna pepe in polvere"],
  "cayenne-pepper": ["cayenna pepe"],
  "celeriac-root": ["ingrediente celeriac root"],
  "celery-salt": ["sedano sale"],
  "celery-seeds": ["sedano semi"],
  "celery": ["sedano"],
  "cellophane-glass-noodles": ["cellophane vetro noodles"],
  "challah-bread": ["challah pane"],
  "cheddar-cheese": ["cheddar formaggio"],
  "cheese": ["formaggio"],
  "cherries": ["ciliegie"],
  "cherry-freeze-dried": ["ciliegia liofilizzato essiccato"],
  "chestnut-mushrooms": ["castagna funghi"],
  "chia-seeds": ["chia semi"],
  "chicken-breast-raw": ["pollo petto crudo"],
  "chicken-leg-raw": ["pollo coscia crudo"],
  "chicken-sausage": ["pollo salsiccia"],
  "chicken-tenderloins": ["pollo tenderloins"],
  "chicken-thighs-bone-in": ["pollo thighs osso in"],
  "chicken-thighs-boneless": ["pollo thighs boneless"],
  "chicken-wings-raw": ["pollo alette crudo"],
  "chickpeas": ["ceci"],
  "chikoo-sapodilla": ["ingrediente chikoo sapodilla"],
  "chili-flakes": ["peperoncino fiocchi"],
  "chili-oil": ["peperoncino olio"],
  "chinese-cooking-wine": ["chinese da cucina vino"],
  "chinese-sesame-paste": ["chinese sesamo pasta"],
  "chocolate-syrup": ["cioccolato sciroppo"],
  "chokeberries": ["ingrediente chokeberries"],
  "cilantro-dried": ["coriandolo essiccato"],
  "cilantro": ["coriandolo"],
  "cinnamon-ground": ["cannella macinato"],
  "cinnamon-raisin-bagel": ["cannella raisin bagel"],
  "cinnamon-stick": ["cannella bastoncino"],
  "cinnamon-sugar": ["cannella zucchero"],
  "citron": ["ingrediente citron"],
  "clams": ["vongole"],
  "clementine": ["ingrediente clementine"],
  "clotted-cream": ["denso crema"],
  "cloudberry": ["ingrediente cloudberry"],
  "cloves-ground": ["chiodi di garofano macinato"],
  "cloves": ["chiodi di garofano"],
  "cocoa-powder": ["cocoa in polvere"],
  "coconut-sugar": ["cocco zucchero"],
  "cod-fillet-raw": ["merluzzo filetto crudo"],
  "coffee-beans": ["caffe fagioli"],
  "coffee-creamer": ["caffe panna"],
  "coffee-cup": ["caffe tazza"],
  "coho-salmon-fillet-raw": ["coho salmone filetto crudo"],
  "colby-jack-cheese": ["colby jack formaggio"],
  "collard-greens": ["cavolo verdure"],
  "condensed-milk": ["condensato latte"],
  "coriander-ground": ["coriandolo macinato"],
  "coriander-seeds": ["coriandolo semi"],
  "corn-chips": ["mais patatine"],
  "corn-flour": ["mais farina"],
  "corn-syrup": ["mais sciroppo"],
  "corn-tortillas": ["mais tortillas"],
  "corn": ["mais"],
  "cornbread": ["pane di mais"],
  "corned-beef-brisket-raw": ["corned manzo brisket crudo"],
  "cornmeal": ["ingrediente cornmeal"],
  "cotija-cheese": ["cotija formaggio"],
  "cottage-cheese": ["cottage formaggio"],
  "crackers": ["cracker"],
  "craisins": ["ingrediente craisins"],
  "cranberries": ["ingrediente cranberries"],
  "crawfish-cooked": ["crawfish cotto"],
  "cream-cheese": ["crema formaggio"],
  "croissant": ["ingrediente croissant"],
  "crostini-slices": ["crostini fette"],
  "croutons": ["ingrediente croutons"],
  "cucumber": ["cetriolo"],
  "cumin-ground": ["cumino macinato"],
  "cumin-seeds": ["cumino semi"],
  "curly-kale": ["curly cavolo riccio"],
  "currants": ["ribes"],
  "curry-powder": ["curry in polvere"],
  "custard-apple": ["custard mela"],
  "cuttlefish": ["ingrediente cuttlefish"],
  "dahi-indian-yogurt": ["dahi indiano yogurt"],
  "daikon-radish": ["daikon ravanello"],
  "dark-brown-sugar": ["scuro marrone zucchero"],
  "dark-chocolate-bar": ["scuro cioccolato barra"],
  "dark-chocolate-chips": ["scuro cioccolato patatine"],
  "dark-chocolate-chunks": ["scuro cioccolato chunks"],
  "dark-red-kidney-beans-canned": ["scuro rosso kidney fagioli in scatola"],
  "dark-red-kidney-beans-dry": ["scuro rosso kidney fagioli secco"],
  "deli-ham": ["gastronomia prosciutto"],
  "deli-roast-beef": ["gastronomia arrosto manzo"],
  "dijon-mustard": ["digione senape"],
  "dill-dried": ["aneto essiccato"],
  "dill-pickles": ["aneto pickles"],
  "dragon-fruit-pitaya": ["dragon frutta pitaya"],
  "dressed-trout": ["dressed trota"],
  "dried-black-djondjon-mushrooms": ["essiccato nero djondjon funghi"],
  "dried-chinese-mushrooms": ["essiccato chinese funghi"],
  "dried-goji-berries": ["essiccato goji bacche"],
  "dried-red-chilies": ["essiccato rosso chilies"],
  "dumpling-wrappers": ["raviolo involucri"],
  "durian": ["ingrediente durian"],
  "edam-cheese": ["edam formaggio"],
  "edamame-pods": ["edamame baccelli"],
  "egg-noodles": ["uovo noodles"],
  "egg": ["uovo"],
  "eggplant": ["melanzana"],
  "elbow-macaroni": ["gomito macaroni"],
  "elderberries": ["bacche di sambuco"],
  "endive": ["indivia"],
  "english-muffin": ["inglese muffin"],
  "enoki-mushroom": ["ingrediente enoki mushroom"],
  "everything-bagel-seasoning": ["ingrediente everything bagel seasoning"],
  "everything-bagel": ["ingrediente everything bagel"],
  "fennel-seeds": ["finocchio semi"],
  "fennel": ["finocchio"],
  "fenugreek-seeds": ["fieno greco semi"],
  "feta-cheese": ["feta formaggio"],
  "fettuccine": ["ingrediente fettuccine"],
  "fig": ["ingrediente fig"],
  "flatbread": ["ingrediente flatbread"],
  "flax-seeds": ["flax semi"],
  "flounder-fillet-raw": ["passera filetto crudo"],
  "flour-tortillas": ["farina tortillas"],
  "focaccia": ["ingrediente focaccia"],
  "fresh-mozzarella": ["mozzarella fresca"],
  "fried-onions": ["fritto onions"],
  "fruit-jam": ["frutta marmellata"],
  "garlic-bagel": ["aglio bagel"],
  "garlic-bulb": ["aglio bulbo"],
  "garlic-powder": ["aglio in polvere"],
  "ghee": ["ingrediente ghee"],
  "ghost-pepper-bhut-jolokia": ["ghost pepe bhut jolokia"],
  "ginger-ground": ["zenzero macinato"],
  "ginger-root": ["zenzero root"],
  "goat-cheese": ["capra formaggio"],
  "gochugaru-flakes": ["gochugaru fiocchi"],
  "gochujang": ["ingrediente gochujang"],
  "golden-beet": ["dorato barbabietola"],
  "gooseberry": ["ingrediente gooseberry"],
  "gorgonzola-cheese": ["gorgonzola formaggio"],
  "gouda-cheese": ["gouda formaggio"],
  "graham-cracker-crust": ["graham cracker crosta"],
  "granadilla": ["ingrediente granadilla"],
  "grapefruit": ["ingrediente grapefruit"],
  "great-northern-beans-dry": ["great northern fagioli secco"],
  "green-apple": ["mela verde"],
  "green-bell-pepper": ["verde campana pepe"],
  "green-cardamom": ["verde cardamomo"],
  "green-grapes": ["verde uva"],
  "green-leaf-lettuce": ["verde leaf lattuga"],
  "green-lime": ["verde lime"],
  "green-mung-beans-sabut-moong": ["verde mung fagioli sabut moong"],
  "green-tomato": ["verde pomodoro"],
  "ground-beef-raw": ["macinato manzo crudo"],
  "ground-coffee-coarse": ["macinato caffe coarse"],
  "ground-coffee-fine": ["macinato caffe fine"],
  "ground-lamb-raw": ["macinato agnello crudo"],
  "ground-sausage": ["macinato salsiccia"],
  "grouper-fillet-raw": ["grouper filetto crudo"],
  "gruyere-cheese": ["gruyere formaggio"],
  "guacamole": ["ingrediente guacamole"],
  "guava": ["ingrediente guava"],
  "gulkand-rose-petal-jam": ["gulkand rose petal marmellata"],
  "gyoza-wrappers": ["gyoza involucri"],
  "habanero-pepper": ["habanero pepe"],
  "haddock-fillet-raw": ["haddock filetto crudo"],
  "half-and-half": ["ingrediente half and half"],
  "halibut-steak-raw": ["halibut bistecca crudo"],
  "halloumi-cheese": ["halloumi formaggio"],
  "ham-bone-in": ["prosciutto osso in"],
  "ham-steak-raw": ["prosciutto bistecca crudo"],
  "hard-taco-shells": ["duro taco gusci"],
  "harissa-paste": ["harissa pasta"],
  "haskap-berry": ["haskap bacca"],
  "havarti-cheese": ["havarti formaggio"],
  "hawaiian-rolls": ["ingrediente hawaiian rolls"],
  "hawthorn-berries": ["biancospino bacche"],
  "heavy-cream": ["densa crema"],
  "heirloom-tomato": ["heirloom pomodoro"],
  "herbes-de-provenc": ["erbe de provenc"],
  "honey": ["miele"],
  "honeydew": ["ingrediente honeydew"],
  "horse-gram-kulthi": ["ingrediente horse gram kulthi"],
  "horseradish": ["ingrediente horseradish"],
  "hot-dog": ["hot dog"],
  "hot-sauce": ["piccante salsa"],
  "huckleberries": ["ingrediente huckleberries"],
  "hummus": ["ingrediente hummus"],
  "iceberg-lettuce": ["iceberg lattuga"],
  "indian-papad": ["indiano papad"],
  "indian-sev": ["indiano sev"],
  "italian-seasoning": ["italiano seasoning"],
  "jackfruit": ["ingrediente jackfruit"],
  "jaggery": ["ingrediente jaggery"],
  "jalapeno": ["ingrediente jalapeno"],
  "jicama": ["ingrediente jicama"],
  "jujube": ["ingrediente jujube"],
  "just-egg": ["just uovo"],
  "kaffir-lime": ["ingrediente kaffir lime"],
  "kefir": ["ingrediente kefir"],
  "ketchup": ["ingrediente ketchup"],
  "khoya": ["ingrediente khoya"],
  "kielbasa-sausage": ["kielbasa salsiccia"],
  "kimchi": ["ingrediente kimchi"],
  "king-trumpet-mushroom": ["reale trumpet mushroom"],
  "kiwi": ["ingrediente kiwi"],
  "kokum": ["ingrediente kokum"],
  "kombu": ["ingrediente kombu"],
  "kumquats": ["ingrediente kumquats"],
  "lamb-chops-raw": ["agnello chops crudo"],
  "lamb-leg-boneless-raw": ["agnello coscia boneless crudo"],
  "lamb-shank-raw": ["agnello shank crudo"],
  "lamb-shoulder-raw": ["agnello spalla crudo"],
  "leek": ["porro"],
  "lemon-sole-fillet-raw": ["limone sogliola filetto crudo"],
  "lemon": ["limone"],
  "lemongrass": ["ingrediente lemongrass"],
  "lettuce": ["lattuga"],
  "light-brown-sugar": ["chiaro marrone zucchero"],
  "light-red-kidney-beans-canned": ["chiaro rosso kidney fagioli in scatola"],
  "light-red-kidney-beans-dry": ["chiaro rosso kidney fagioli secco"],
  "lingonberries": ["ingrediente lingonberries"],
  "linguine": ["ingrediente linguine"],
  "lions-mane-mushroom": ["ingrediente lions mane mushroom"],
  "little-gem-lettuce": ["little gem lattuga"],
  "lobster-tail-raw": ["aragosta coda crudo"],
  "loganberry": ["ingrediente loganberry"],
  "longan": ["ingrediente longan"],
  "lychee": ["ingrediente lychee"],
  "mace": ["ingrediente mace"],
  "mache-lambs-lettuce": ["mache lambs lattuga"],
  "mackerel-fillet-smoked": ["sgombro filetto affumicato"],
  "mackerel": ["sgombro"],
  "mahi-mahi-fillet-raw": ["mahi mahi filetto crudo"],
  "manchego-cheese": ["manchego formaggio"],
  "mandarin": ["mandarino"],
  "mango": ["ingrediente mango"],
  "maple-syrup": ["acero sciroppo"],
  "margarine": ["margarina"],
  "marjoram-dried": ["maggiorana essiccato"],
  "mascarpone-cheese": ["mascarpone formaggio"],
  "matcha-latte-iced": ["matcha latte freddo"],
  "matcha-powder": ["matcha in polvere"],
  "matsutake-mushroom": ["ingrediente matsutake mushroom"],
  "matzo": ["ingrediente matzo"],
  "mayonnaise": ["maionese"],
  "melon": ["melone"],
  "meyer-lemon": ["meyer limone"],
  "mild-cheddar-cheese": ["mild cheddar formaggio"],
  "milk-chocolate-bar": ["latte cioccolato barra"],
  "milk-chocolate-chips": ["latte cioccolato patatine"],
  "milk-chocolate-chunks": ["latte cioccolato chunks"],
  "milk-glass": ["latte vetro"],
  "milkfish-bangus": ["ingrediente milkfish bangus"],
  "millet": ["miglio"],
  "mint-dried": ["menta essiccato"],
  "mint-leaves": ["menta foglie"],
  "mirin": ["ingrediente mirin"],
  "molasses": ["melassa"],
  "monkfish-tail-fillet-raw": ["coda di rospo coda filetto crudo"],
  "monterey-jack-cheese": ["monterey jack formaggio"],
  "morel-mushrooms": ["spugnola funghi"],
  "moth-beans-matki": ["moth fagioli matki"],
  "mulberries": ["ingrediente mulberries"],
  "multigrain-bagel": ["ingrediente multigrain bagel"],
  "mustard-greens": ["senape verdure"],
  "mustard-seeds-ground": ["senape semi macinato"],
  "mutton-raw": ["mutton crudo"],
  "naan-bread": ["naan pane"],
  "napa-cabbage": ["napa cavolo"],
  "navy-beans-canned": ["navy fagioli in scatola"],
  "navy-beans-dry": ["navy fagioli secco"],
  "nectarine": ["ingrediente nectarine"],
  "neyyappam-fritters": ["ingrediente neyyappam fritters"],
  "nori-sheet": ["ingrediente nori sheet"],
  "nutella": ["ingrediente nutella"],
  "nutmeg-ground": ["noce moscata macinato"],
  "nutmeg": ["noce moscata"],
  "nutritional-yeast": ["ingrediente nutritional yeast"],
  "oat-bran-bagel": ["ingrediente oat bran bagel"],
  "oat-flour": ["oat farina"],
  "oats": ["avena"],
  "octupus-raw": ["octupus crudo"],
  "okra": ["ingrediente okra"],
  "olive-oil": ["olio d oliva"],
  "olive-tapenade": ["oliva tapenade"],
  "olives": ["olive"],
  "onion-bagel": ["cipolla bagel"],
  "onion-powder": ["cipolla in polvere"],
  "oolong-tea-leaves": ["oolong te foglie"],
  "orange-bell-pepper": ["arancione campana pepe"],
  "orange-marmalade": ["arancione marmalade"],
  "orange": ["arancione"],
  "oregano-dried": ["origano essiccato"],
  "oregon-grapes": ["oregon uva"],
  "oyster-mushrooms": ["ostrica funghi"],
  "oyster": ["ostrica"],
  "paccheri": ["ingrediente paccheri"],
  "pancetta": ["ingrediente pancetta"],
  "panettone": ["ingrediente panettone"],
  "panko-flakes": ["panko fiocchi"],
  "papaya": ["ingrediente papaya"],
  "pappardelle": ["ingrediente pappardelle"],
  "paprika": ["ingrediente paprika"],
  "parmessan-cheese": ["parmigiano"],
  "parsley-dried": ["prezzemolo essiccato"],
  "parsley": ["prezzemolo"],
  "passion-fruit": ["passion frutta"],
  "pastrami": ["ingrediente pastrami"],
  "peach-freeze-dried-slices": ["pesca liofilizzato essiccato fette"],
  "peach": ["pesca"],
  "peanut-butter": ["arachide burro"],
  "pear-freeze-dried-slices": ["pera liofilizzato essiccato fette"],
  "pear": ["pera"],
  "pearl-onion": ["pearl cipolla"],
  "pecorino-romano-cheese": ["pecorino romano formaggio"],
  "penne-lisce": ["ingrediente penne lisce"],
  "penne-rigate": ["ingrediente penne rigate"],
  "pepperoni": ["ingrediente pepperoni"],
  "peri-peri-sauce": ["peri peri salsa"],
  "persimmon": ["ingrediente persimmon"],
  "pesto": ["ingrediente pesto"],
  "phyllo-dough": ["ingrediente phyllo dough"],
  "pickled-jalapenos": ["sottaceto jalapenos"],
  "pickled-onions": ["sottaceto onions"],
  "pie-crust": ["torta crosta"],
  "pike-fish": ["luccio pesce"],
  "pimento-pepper": ["pimento pepe"],
  "pineapple": ["ananas"],
  "pinto-beans-canned": ["pinto fagioli in scatola"],
  "pinto-beans-dry": ["pinto fagioli secco"],
  "pioppino-mushrooms": ["pioppino funghi"],
  "pistachios": ["pistacchi"],
  "pita-bread": ["pita pane"],
  "pita-chips": ["pita patatine"],
  "pizza-dough": ["ingrediente pizza dough"],
  "plain-bagel": ["ingrediente plain bagel"],
  "plantain-chips": ["plantain patatine"],
  "plantain": ["ingrediente plantain"],
  "plum": ["ingrediente plum"],
  "poblano-pepper": ["poblano pepe"],
  "pollock-fillet-raw": ["pollock filetto crudo"],
  "pomegranate": ["ingrediente pomegranate"],
  "pomelo": ["ingrediente pomelo"],
  "popcorn-kernels": ["popcorn chicchi"],
  "popcorn": ["ingrediente popcorn"],
  "poppy-seed-bagel": ["papavero seed bagel"],
  "poppy-seeds": ["papavero semi"],
  "porcini-mushroom": ["ingrediente porcini mushroom"],
  "pork-belly-raw": ["maiale belly crudo"],
  "pork-chops-raw": ["maiale chops crudo"],
  "pork-loin-roast-raw": ["maiale lonza arrosto crudo"],
  "pork-shoulder-raw": ["maiale spalla crudo"],
  "pork-spare-ribs-raw": ["maiale spare costine crudo"],
  "pork-tenderloin-raw": ["maiale filetto crudo"],
  "portobello-mushroom": ["ingrediente portobello mushroom"],
  "potato-bread": ["patata pane"],
  "potato-chips": ["patata patatine"],
  "potato": ["patata"],
  "prawn-raw": ["gambero crudo"],
  "preserved-mustard-greens": ["conservato senape verdure"],
  "pretzel": ["ingrediente pretzel"],
  "prosciutto": ["ingrediente prosciutto"],
  "provolone-cheese": ["provolone formaggio"],
  "prunes": ["prugne secche"],
  "puff-pastry-dough": ["ingrediente puff pastry dough"],
  "puffball-mushroom": ["ingrediente puffball mushroom"],
  "pumpernickel-bagel": ["ingrediente pumpernickel bagel"],
  "pumpernickel-bread": ["pumpernickel pane"],
  "pumpkin-seeds-pepitas": ["zucca semi pepitas"],
  "pumpkin": ["zucca"],
  "quince": ["ingrediente quince"],
  "quinoa": ["ingrediente quinoa"],
  "radicchio": ["ingrediente radicchio"],
  "rainbow-trout": ["rainbow trota"],
  "raisins": ["uvetta"],
  "ramen-noodles": ["ingrediente ramen noodles"],
  "rarramundi-fillet-raw": ["rarramundi filetto crudo"],
  "raspberry-freeze-dried": ["lampone liofilizzato essiccato"],
  "raspberry": ["lampone"],
  "raw-peanuts": ["crudo arachidi"],
  "red-apple": ["mela rossa"],
  "red-bell-pepper": ["rosso campana pepe"],
  "red-cabbage": ["rosso cavolo"],
  "red-cherries": ["rosso ciliegie"],
  "red-crab-cooked": ["rosso granchio cotto"],
  "red-fresno-pepper": ["rosso fresno pepe"],
  "red-grapes": ["rosso uva"],
  "red-leaf-lettuce": ["rosso leaf lattuga"],
  "red-lobster-cooked": ["rosso aragosta cotto"],
  "red-lobster-mushroom": ["rosso aragosta mushroom"],
  "red-onion": ["cipolla rossa"],
  "red-paprika-powder": ["rosso paprika in polvere"],
  "red-snapper": ["rosso dentice"],
  "red-wine-vinegar": ["aceto di vino rosso"],
  "relish": ["ingrediente relish"],
  "rhubarb": ["ingrediente rhubarb"],
  "rice-cake": ["riso torta"],
  "rice-noodles": ["riso noodles"],
  "rice-paper": ["riso paper"],
  "rice-vermicelli-noodles": ["riso vermicelli noodles"],
  "rice-vinegar": ["riso aceto"],
  "ricotta-cheese": ["ricotta formaggio"],
  "rigatoni": ["ingrediente rigatoni"],
  "rockfish-fillet-raw": ["scorfano filetto crudo"],
  "romaine-lettuce": ["romana lattuga"],
  "roquefort-cheese": ["roquefort formaggio"],
  "rose-petals-dry": ["rose petals secco"],
  "rosehip": ["ingrediente rosehip"],
  "rosemary-dried": ["rosmarino essiccato"],
  "rosemary-sprig": ["rosmarino rametto"],
  "rotisserie-chicken": ["rotisserie pollo"],
  "rustic-italian-bread": ["rustic italiano pane"],
  "rye-bread-slice": ["segale pane fetta"],
  "saffron": ["zafferano"],
  "sage-dried": ["salvia essiccato"],
  "salami": ["ingrediente salami"],
  "salmon-fillet-raw": ["salmone filetto crudo"],
  "salmon-roe-ikura": ["salmone uova ikura"],
  "salsa": ["ingrediente salsa"],
  "salt-cod-dried": ["sale merluzzo essiccato"],
  "salt-shaker": ["sale shaker"],
  "salt": ["sale"],
  "sambal-oelek": ["ingrediente sambal oelek"],
  "sardines-tin": ["sardine tin"],
  "saskatoon-berries": ["saskatoon bacche"],
  "sauerkraut": ["ingrediente sauerkraut"],
  "sausage": ["salsiccia"],
  "scotch-bonnet-pepper": ["scotch bonnet pepe"],
  "sea-bass": ["mare bass"],
  "sea-bream": ["mare bream"],
  "sea-buckthorn-berries": ["mare olivello bacche"],
  "sea-scallop-raw": ["mare capesanta crudo"],
  "seitan-shredded": ["ingrediente seitan shredded"],
  "serrano-pepper": ["serrano pepe"],
  "sesame-oil": ["sesamo olio"],
  "sesame-seed-bagel": ["sesamo seed bagel"],
  "sesame-seeds": ["sesamo semi"],
  "shallot": ["scalogno"],
  "shiitake-mushroom": ["ingrediente shiitake mushroom"],
  "shirataki-noodles": ["ingrediente shirataki noodles"],
  "shishito-peppers": ["shishito peperoni"],
  "shredded-pulled-pork": ["shredded sfilacciato maiale"],
  "shrimp-dried": ["gamberetto essiccato"],
  "sichuan-peppercorns": ["ingrediente sichuan peppercorns"],
  "silken-tofu": ["setoso tofu"],
  "silver-pomfret": ["argento pomfret"],
  "skyr": ["ingrediente skyr"],
  "sloe-berries": ["sloe bacche"],
  "smoked-paprika": ["affumicato paprika"],
  "smoked-sausage": ["affumicato salsiccia"],
  "snow-fungus": ["neve fungus"],
  "soba-noodles": ["ingrediente soba noodles"],
  "sockeye-salmon-fillet-raw": ["sockeye salmone filetto crudo"],
  "sole-fillet-raw": ["sogliola filetto crudo"],
  "somen-noodles": ["ingrediente somen noodles"],
  "sour-cherries": ["acido ciliegie"],
  "sour-cream": ["acido crema"],
  "sourdough-bread": ["sourdough pane"],
  "sourdough-starter": ["ingrediente sourdough starter"],
  "soy-chunks": ["soia chunks"],
  "soy-curls": ["soia curls"],
  "soy-sauce-dark": ["soia salsa scuro"],
  "soy-sauce-light": ["soia salsa chiaro"],
  "soy-sauce": ["soia salsa"],
  "spaghetti": ["ingrediente spaghetti"],
  "spanish-chorizo": ["ingrediente spanish chorizo"],
  "spinach": ["spinaci"],
  "split-chickpeas-chana-dal": ["ceci spezzati chana dal"],
  "split-green-mung-beans": ["split verde mung fagioli"],
  "split-pigeon-peas-toor-dal": ["split pigeon piselli toor dal"],
  "split-red-lentil-masoor-dal": ["lenticchie rosse masoor dal"],
  "split-white-urad-dal": ["split bianco urad dal"],
  "split-yellow-mung-beans-moong-dal": ["split giallo mung fagioli moong dal"],
  "sprinkles-shaker": ["ingrediente sprinkles shaker"],
  "sprouted-moth-beans": ["sprouted moth fagioli"],
  "sprouted-mung-beans": ["sprouted mung fagioli"],
  "squid-raw": ["squid crudo"],
  "sriracha-sauce": ["sriracha salsa"],
  "star-anise": ["ingrediente star anise"],
  "star-fruit": ["star frutta"],
  "steelhead-trout-fillet-raw": ["steelhead trota filetto crudo"],
  "stevia": ["ingrediente stevia"],
  "stilton-cheese": ["stilton formaggio"],
  "straw-mushrooms": ["straw funghi"],
  "strawberry-freeze-dried-slices": ["fragola liofilizzato essiccato fette"],
  "strawberry-freeze-dried": ["fragola liofilizzato essiccato"],
  "strawberry": ["fragola"],
  "sugar-granulated": ["zucchero granulated"],
  "sultanas": ["ingrediente sultanas"],
  "sun-dried-tomato": ["sole essiccato pomodoro"],
  "sunflower-seeds-shelled": ["girasole semi shelled"],
  "surimi": ["ingrediente surimi"],
  "sweet-potato": ["dolce patata"],
  "swiss-chard": ["svizzero bietola"],
  "swiss-cheese": ["svizzero formaggio"],
  "swordfish-steak-raw": ["pesce spada bistecca crudo"],
  "t-bone-beef-steak": ["t osso manzo bistecca"],
  "tamari": ["ingrediente tamari"],
  "tamarillo": ["ingrediente tamarillo"],
  "tamarind-paste": ["tamarindo pasta"],
  "tamarind": ["tamarindo"],
  "tangelo": ["ingrediente tangelo"],
  "tarragon": ["ingrediente tarragon"],
  "tater-tots": ["tater bocconcini"],
  "tea-bag": ["te bag"],
  "tea-sachet": ["te sachet"],
  "tempeh": ["ingrediente tempeh"],
  "textured-vegetable-protein-tvp": ["textured vegetale protein tvp"],
  "thai-red-chili": ["thai rosso peperoncino"],
  "thyme-dried": ["timo essiccato"],
  "thyme-sprig": ["timo rametto"],
  "tilapia-fillet-raw": ["tilapia filetto crudo"],
  "tofu-firm": ["tofu compatto"],
  "tomato-juice": ["pomodoro succo"],
  "tomato-paste": ["concentrato di pomodoro"],
  "tomato-puree": ["passata di pomodoro"],
  "tomato": ["pomodoro"],
  "tortilla-chips": ["tortilla patatine"],
  "tostada-shell": ["ingrediente tostada shell"],
  "trinidad-scorpion-pepper": ["trinidad scorpion pepe"],
  "tuna-steak-raw": ["tonno bistecca crudo"],
  "turbot-fish": ["turbot pesce"],
  "turmeric-powder": ["curcuma in polvere"],
  "tuscan-kale": ["tuscan cavolo riccio"],
  "udon-noodles": ["ingrediente udon noodles"],
  "unagi-eel-grilled": ["ingrediente unagi eel grilled"],
  "vanilla-extract": ["vaniglia extract"],
  "vanilla-pods": ["vaniglia baccelli"],
  "veal-steak-raw": ["vitello bistecca crudo"],
  "vegetable-shortening": ["vegetale shortening"],
  "venison-steak-raw": ["cervo bistecca crudo"],
  "waffle-cone": ["waffle cono"],
  "wakame-seaweed": ["ingrediente wakame seaweed"],
  "walleye-fillet-raw": ["walleye filetto crudo"],
  "walnuts": ["noci"],
  "wasabi-paste": ["wasabi pasta"],
  "water-chestnuts-canned": ["acqua chestnuts in scatola"],
  "watercress": ["ingrediente watercress"],
  "watermelon": ["anguria"],
  "white-beach-mushrooms": ["bianco beach funghi"],
  "white-button-mushroom": ["bianco button mushroom"],
  "white-chickpeas-kabuli-chana": ["ceci bianchi kabuli chana"],
  "white-chocolate-bar": ["bianco cioccolato barra"],
  "white-chocolate-chips": ["bianco cioccolato patatine"],
  "white-chocolate-chunks": ["bianco cioccolato chunks"],
  "white-field-mushroom": ["bianco campo mushroom"],
  "white-flour": ["bianco farina"],
  "white-onion": ["cipolla bianca"],
  "white-pepper": ["bianco pepe"],
  "white-rice-bowl": ["ciotola di riso bianco"],
  "white-tea-leaves": ["bianco te foglie"],
  "white-truffle": ["bianco tartufo"],
  "white-vinegar": ["aceto bianco"],
  "whole-wheat-bagel": ["bagel integrale"],
  "whole-wheat-flour": ["farina integrale"],
  "whole-wheat-tortillas": ["tortillas integrali"],
  "wild-mushrooms": ["wild funghi"],
  "yam": ["ingrediente yam"],
  "yellow-bell-pepper": ["giallo campana pepe"],
  "yellow-mustard-seeds": ["giallo senape semi"],
  "yellow-mustard": ["giallo senape"],
  "yellow-onion": ["cipolla gialla"],
  "yellow-zucchini": ["giallo zucchina"],
  "yellowtail-hamachi-raw": ["yellowtail hamachi crudo"],
  "yerba-mate-tea": ["yerba mate te"],
  "yogurt": ["ingrediente yogurt"],
  "yuba-dried-tofu-skin": ["yuba essiccato tofu skin"],
  "yuzu": ["ingrediente yuzu"],
  "ziti": ["ingrediente ziti"],
  "zucchini": ["zucchina"],
};
