/* eslint-env node */
/* eslint-disable no-undef */
const fs = require("fs");
const path = require("path");

const root = path.resolve(__dirname, "..");
const iconDir = path.join(root, "assets", "images", "food-icons");
const outFile = path.join(root, "utils", "foodIconAliasesIt.ts");

const files = fs
  .readdirSync(iconDir)
  .filter((f) => f.endsWith(".png"))
  .sort((a, b) => a.localeCompare(b));

const TOKEN_MAP = {
  acorn: "ghianda",
  agave: "agave",
  alfalfa: "erba medica",
  almond: "mandorla",
  almonds: "mandorle",
  amber: "ambra",
  american: "americano",
  anchovies: "acciughe",
  angel: "angelo",
  apple: "mela",
  applesauce: "purea di mela",
  apricot: "albicocca",
  arctic: "artico",
  arugula: "rucola",
  asparagus: "asparagi",
  avocado: "avocado",
  baby: "baby",
  bacon: "pancetta",
  bagel: "bagel",
  baguette: "baguette",
  balsamic: "balsamico",
  banana: "banana",
  bar: "barra",
  basil: "basilico",
  bay: "alloro",
  bean: "fagiolo",
  beans: "fagioli",
  beef: "manzo",
  beet: "barbabietola",
  beets: "barbabietole",
  bell: "campana",
  berries: "bacche",
  berry: "bacca",
  black: "nero",
  blackberry: "mora",
  blackcurrant: "ribes nero",
  blue: "blu",
  blueberry: "mirtillo",
  bone: "osso",
  bok: "bok",
  bologna: "bologna",
  boba: "boba",
  boconcini: "bocconcini",
  bouillon: "brodo",
  boysenberry: "boysenberry",
  bread: "pane",
  breadstick: "grissino",
  breast: "petto",
  brie: "brie",
  broccoli: "broccoli",
  broth: "brodo",
  brown: "marrone",
  brussels: "bruxelles",
  buckthorn: "olivello",
  bulgogi: "bulgogi",
  bulb: "bulbo",
  burrata: "burrata",
  butter: "burro",
  buttermilk: "latticello",
  cabbage: "cavolo",
  cacao: "cacao",
  caffe: "caffe",
  cake: "torta",
  calamansi: "calamansi",
  camembert: "camembert",
  canadian: "canadese",
  candied: "candito",
  canned: "in scatola",
  capers: "capperi",
  capsicum: "peperone",
  caramel: "caramello",
  cardamom: "cardamomo",
  carrot: "carota",
  carrots: "carote",
  cashews: "anacardi",
  cassava: "manioca",
  catfish: "pesce gatto",
  caviar: "caviale",
  cayenne: "cayenna",
  celery: "sedano",
  chard: "bietola",
  cheddar: "cheddar",
  cheese: "formaggio",
  cherries: "ciliegie",
  cherry: "ciliegia",
  chestnut: "castagna",
  chickpeas: "ceci",
  chicken: "pollo",
  chili: "peperoncino",
  chillies: "peperoncini",
  chips: "patatine",
  chive: "erba cipollina",
  chocolate: "cioccolato",
  chorizo: "chorizo",
  cinnamon: "cannella",
  cider: "sidro",
  cilantro: "coriandolo",
  clam: "vongola",
  clams: "vongole",
  cloves: "chiodi di garofano",
  clotted: "denso",
  coconut: "cocco",
  cod: "merluzzo",
  coffee: "caffe",
  colby: "colby",
  collard: "cavolo",
  cone: "cono",
  condensed: "condensato",
  cookies: "biscotti",
  cooked: "cotto",
  cooking: "da cucina",
  coriander: "coriandolo",
  corn: "mais",
  cornbread: "pane di mais",
  crackers: "cracker",
  crab: "granchio",
  cream: "crema",
  creamer: "panna",
  crisps: "patatine",
  croissant: "croissant",
  crumbs: "pangrattato",
  crust: "crosta",
  cucumber: "cetriolo",
  cumin: "cumino",
  cup: "tazza",
  curd: "cagliata",
  currant: "ribes",
  currants: "ribes",
  curry: "curry",
  dark: "scuro",
  daikon: "daikon",
  deli: "gastronomia",
  dijon: "digione",
  dill: "aneto",
  dried: "essiccato",
  drink: "bevanda",
  dry: "secco",
  dumpling: "raviolo",
  durian: "durian",
  egg: "uovo",
  eggplant: "melanzana",
  elderberries: "bacche di sambuco",
  elbow: "gomito",
  endive: "indivia",
  english: "inglese",
  enoki: "enoki",
  extra: "extra",
  eye: "occhio",
  fettuccine: "fettuccine",
  fennel: "finocchio",
  fenugreek: "fieno greco",
  feta: "feta",
  field: "campo",
  fillet: "filetto",
  fine: "fine",
  firm: "compatto",
  fish: "pesce",
  flakes: "fiocchi",
  flour: "farina",
  flounder: "passera",
  focaccia: "focaccia",
  freeze: "liofilizzato",
  fresh: "fresco",
  fries: "patatine fritte",
  fried: "fritto",
  fruit: "frutta",
  fungi: "funghi",
  garlic: "aglio",
  ghee: "ghee",
  ginger: "zenzero",
  glass: "vetro",
  gochujang: "gochujang",
  goat: "capra",
  golden: "dorato",
  gorgonzola: "gorgonzola",
  gouda: "gouda",
  graham: "graham",
  grapes: "uva",
  green: "verde",
  greens: "verdure",
  ground: "macinato",
  gruyere: "gruyere",
  guacamole: "guacamole",
  guava: "guava",
  halloumi: "halloumi",
  ham: "prosciutto",
  hard: "duro",
  harissa: "harissa",
  hass: "hass",
  hawthorn: "biancospino",
  heart: "cuore",
  heavy: "densa",
  herb: "erba",
  herbes: "erbe",
  herring: "aringa",
  honey: "miele",
  hot: "piccante",
  hummus: "hummus",
  ice: "ghiaccio",
  iceberg: "iceberg",
  iced: "freddo",
  indian: "indiano",
  ikura: "ikura",
  italian: "italiano",
  jalapeno: "jalapeno",
  jam: "marmellata",
  jasmine: "gelsomino",
  juice: "succo",
  kale: "cavolo riccio",
  ketchup: "ketchup",
  kefir: "kefir",
  kernels: "chicchi",
  kimchi: "kimchi",
  king: "reale",
  kiwi: "kiwi",
  lamb: "agnello",
  leaves: "foglie",
  leek: "porro",
  leg: "coscia",
  lemon: "limone",
  lentil: "lenticchia",
  lentils: "lenticchie",
  lettuce: "lattuga",
  light: "chiaro",
  lime: "lime",
  linguine: "linguine",
  liver: "fegato",
  loaf: "pagnotta",
  lobster: "aragosta",
  longan: "longan",
  loin: "lonza",
  lychee: "lychee",
  mackerel: "sgombro",
  mahi: "mahi",
  manchego: "manchego",
  mandarin: "mandarino",
  mango: "mango",
  maple: "acero",
  margarine: "margarina",
  marjoram: "maggiorana",
  masala: "masala",
  mascarpone: "mascarpone",
  matcha: "matcha",
  mayonnaise: "maionese",
  medallion: "medaglione",
  melon: "melone",
  milk: "latte",
  millet: "miglio",
  mince: "tritato",
  mini: "mini",
  mint: "menta",
  mirin: "mirin",
  molasses: "melassa",
  monkfish: "coda di rospo",
  monterey: "monterey",
  morel: "spugnola",
  mortadella: "mortadella",
  moth: "moth",
  mozzarella: "mozzarella",
  mushrooms: "funghi",
  mustard: "senape",
  mussels: "cozze",
  muton: "montone",
  napa: "napa",
  nectar: "nettare",
  noodles: "noodles",
  nori: "nori",
  nutella: "nutella",
  nutmeg: "noce moscata",
  oats: "avena",
  octopus: "polpo",
  oil: "olio",
  olive: "oliva",
  olives: "olive",
  onion: "cipolla",
  orange: "arancione",
  oregano: "origano",
  oyster: "ostrica",
  oysters: "ostriche",
  paccheri: "paccheri",
  pancetta: "pancetta",
  panko: "panko",
  papad: "papad",
  papaya: "papaya",
  paprika: "paprika",
  parmesan: "parmigiano",
  parsley: "prezzemolo",
  pasta: "pasta",
  paste: "pasta",
  pastrami: "pastrami",
  patties: "polpette",
  peach: "pesca",
  peanut: "arachide",
  peanuts: "arachidi",
  pear: "pera",
  peas: "piselli",
  pecorino: "pecorino",
  pepper: "pepe",
  peppers: "peperoni",
  pepperoni: "pepperoni",
  pesto: "pesto",
  pickled: "sottaceto",
  pie: "torta",
  pike: "luccio",
  pimento: "pimento",
  pineapple: "ananas",
  pinto: "pinto",
  pistachios: "pistacchi",
  pita: "pita",
  pods: "baccelli",
  pollock: "pollock",
  pomelo: "pomelo",
  poppy: "papavero",
  pork: "maiale",
  portobello: "portobello",
  potato: "patata",
  powder: "in polvere",
  prawn: "gambero",
  prawns: "gamberi",
  preserved: "conservato",
  pretzel: "pretzel",
  prosciutto: "prosciutto",
  provolone: "provolone",
  prunes: "prugne secche",
  puree: "purea",
  pumpkin: "zucca",
  pulled: "sfilacciato",
  quail: "quaglia",
  quinoa: "quinoa",
  radish: "ravanello",
  raisins: "uvetta",
  ramen: "ramen",
  raspberry: "lampone",
  raw: "crudo",
  red: "rosso",
  relish: "relish",
  rib: "costola",
  ribs: "costine",
  rice: "riso",
  ricotta: "ricotta",
  rigatoni: "rigatoni",
  roast: "arrosto",
  rockfish: "scorfano",
  roe: "uova",
  romaine: "romana",
  rosemary: "rosmarino",
  round: "rotondo",
  rub: "miscela",
  rye: "segale",
  sablefish: "sablefish",
  saffron: "zafferano",
  sage: "salvia",
  salmon: "salmone",
  salsa: "salsa",
  salt: "sale",
  sardines: "sardine",
  sauce: "salsa",
  sausage: "salsiccia",
  scallion: "cipollotto",
  scallop: "capesanta",
  sea: "mare",
  seeds: "semi",
  sesame: "sesamo",
  shallot: "scalogno",
  shells: "gusci",
  shiitake: "shiitake",
  shoulder: "spalla",
  shrimp: "gamberetto",
  shrooms: "funghi",
  silver: "argento",
  silken: "setoso",
  sirloin: "controfiletto",
  skyr: "skyr",
  slice: "fetta",
  slices: "fette",
  smoked: "affumicato",
  snapper: "dentice",
  snow: "neve",
  soda: "gassosa",
  sole: "sogliola",
  sorghum: "sorgo",
  sour: "acido",
  soy: "soia",
  spaghetti: "spaghetti",
  spinach: "spinaci",
  sprig: "rametto",
  sprigs: "rametti",
  spring: "primavera",
  sprouts: "germogli",
  squash: "zucca",
  steak: "bistecca",
  steelhead: "steelhead",
  stilton: "stilton",
  stick: "bastoncino",
  strips: "strisce",
  strawberry: "fragola",
  sugar: "zucchero",
  sun: "sole",
  sunflower: "girasole",
  sweet: "dolce",
  swiss: "svizzero",
  swordfish: "pesce spada",
  syrup: "sciroppo",
  taco: "taco",
  tail: "coda",
  tamari: "tamari",
  tamarind: "tamarindo",
  tea: "te",
  tenderloin: "filetto",
  tempeh: "tempeh",
  thyme: "timo",
  tilapia: "tilapia",
  tofu: "tofu",
  tomato: "pomodoro",
  tonno: "tonno",
  tortilla: "tortilla",
  tortillas: "tortillas",
  tots: "bocconcini",
  trout: "trota",
  truffle: "tartufo",
  tuna: "tonno",
  turmeric: "curcuma",
  turkey: "tacchino",
  turnip: "rapa",
  udon: "udon",
  unagi: "unagi",
  urad: "urad",
  vanilla: "vaniglia",
  veal: "vitello",
  vegan: "vegano",
  vegetable: "vegetale",
  venison: "cervo",
  vermicelli: "vermicelli",
  vinegar: "aceto",
  wafer: "cialda",
  wakame: "wakame",
  walnuts: "noci",
  wasabi: "wasabi",
  water: "acqua",
  watermelon: "anguria",
  wheat: "grano",
  white: "bianco",
  whole: "intero",
  wings: "alette",
  wine: "vino",
  wrap: "involucro",
  wrappers: "involucri",
  yellow: "giallo",
  yogurt: "yogurt",
  yuba: "yuba",
  yuzu: "yuzu",
  ziti: "ziti",
  zucchini: "zucchina",
};

const KEY_OVERRIDES = {
  "red-apple": "mela rossa",
  "green-apple": "mela verde",
  "yellow-onion": "cipolla gialla",
  "red-onion": "cipolla rossa",
  "white-onion": "cipolla bianca",
  "olive-oil": "olio d oliva",
  "fresh-mozzarella": "mozzarella fresca",
  "parmessan-cheese": "parmigiano",
  "black-pepper-grinder": "macina pepe nero",
  "black-peppercorns": "grani di pepe nero",
  "white-rice-bowl": "ciotola di riso bianco",
  "brown-rice-bowl": "ciotola di riso integrale",
  "split-red-lentil-masoor-dal": "lenticchie rosse masoor dal",
  "split-chickpeas-chana-dal": "ceci spezzati chana dal",
  "white-chickpeas-kabuli-chana": "ceci bianchi kabuli chana",
  "brown-chickpeas-kala-chana": "ceci marroni kala chana",
  "whole-wheat-flour": "farina integrale",
  "whole-wheat-bagel": "bagel integrale",
  "whole-wheat-tortillas": "tortillas integrali",
  "apple-cider-vinegar": "aceto di mele",
  "red-wine-vinegar": "aceto di vino rosso",
  "white-vinegar": "aceto bianco",
  "balsamic-vinegar": "aceto balsamico",
  "tomato-puree": "passata di pomodoro",
  "tomato-paste": "concentrato di pomodoro",
  "hot-dog": "hot dog",
};

function translateToken(token) {
  if (TOKEN_MAP[token]) return TOKEN_MAP[token];
  return token;
}

function buildAlias(key) {
  if (KEY_OVERRIDES[key]) {
    return KEY_OVERRIDES[key];
  }

  const original = key.replace(/-/g, " ").trim();
  const translated = key
    .split("-")
    .map((t) => translateToken(t))
    .join(" ")
    .replace(/\s+/g, " ")
    .trim();

  if (!translated) return `ingrediente ${original}`;
  if (translated === original) return `ingrediente ${translated}`;
  return translated;
}

const entries = files.map((file) => {
  const key = file.replace(/\.png$/i, "");
  const alias = buildAlias(key).replace(/"/g, '\\"');
  return `  "${key}": ["${alias}"],`;
});

const header =
  "// AUTO-GENERATED FILE. DO NOT EDIT.\n" +
  "// Run: node scripts/generateFoodIconItalianAliases.js\n\n";
const body =
  "export const FOOD_ICON_ALIASES_IT: Record<string, string[]> = {\n" +
  entries.join("\n") +
  "\n};\n";

fs.writeFileSync(outFile, header + body, "utf8");

console.log(`Wrote ${files.length} italian aliases to ${path.relative(root, outFile)}`);
